### ISSUE TITLE
$.gevent.publish() is not work on IE8

### ISSUE THREAD

**Issue by ghost** [mmikowski/jquery.event.gevent#1]
Hi!, I follow the SPA book (Really good book anyway)
And now I'm creating my model just similar to the one in the book.
But when I wrote the test for it I just found that the "gevent" lib its not work on IE

My test code look similar like this

``` javascript
var $t = $('<div/>');
$.gevent.subscribe($t, 'login', function(event, name) {
    expect(name).to.be('Pongneng');
    done();
});
```

And in my production code I call the publish mehtod

``` javascript
$.gevent.publish('login', ['Pongneng']);
```

It's caused my test to fail and give me this error: Object doesn't support this property or method
I still don't know what to do about it yet. I just leave it for now because the other browser is work fine.

**Comment by mmikowski** [comment]
It may be due to the version of jQuery you are using.  However, I did not test ie8.

Sent from my ASUS Transformer Pad

-------- Original Message --------

**Comment by ghost** [comment]
I use jQuery 1.10.2. Is that a problem?
Anyway I found that it break on this line

``` javascript
data_list = Array.isArray( data ) ? data : [ data ];
```

IE8 don't have a method isArray (=_=")

I changed to

``` javascript
data_list = data instanceof Array ? data : [ data ];
```

and it work fine. (Not sure it's right or not ha ha)

**Comment by mmikowski** [comment]
Sorry about the delayed response.  The instanceof looks correct at first glance.  A little sniffing around shows your potential pain is much greater for IE 8:

http://whattheheadsaid.com/2010/10/cross-context-isarray-and-internet-explorer

**Comment by mmikowski** [comment]
The current release now uses the jQuery isArray method, which should fix the problem with IE 8.
